# Generated by Django 4.0.5 on 2022-06-12 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_userdata_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='department',
            field=models.CharField(default='B.E', max_length=20),
        ),
    ]
