# Generated by Django 4.0.5 on 2022-06-12 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_userdata_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='department',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
