# Generated by Django 4.0.5 on 2022-06-12 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_alter_userdata_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='department',
        ),
    ]
