# Generated by Django 4.0.5 on 2022-06-12 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_remove_userdata_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='department',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
